import { GET_ALL_POSTS } from '@/graphql/queries';
import { ApolloClient, InMemoryCache } from '@apollo/client'
import Head from 'next/head'
import Link from 'next/link'

export default function Home({posts}) {
  return (
    <div className='font-sans mx-auto max-w-3xl px-4 sm:px-6 md:max-w-5xl bg-slate-50'>
      <Head>
        <title>Dims Blog</title>
        <meta name="description" content='Generated by create next app' />
        <Link rel="icon" href="/favicon.ico"/>
      </Head>
      {/* <h1>Welcome to GoBlog</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras bibendum in est eget vulputate. Sed sit amet mauris leo. Etiam laoreet ut augue ac finibus. </p>
      <br/> */}
      <h2 className='font-bold text-4xl underline'>All Posts</h2>
      {posts.map((val, i) => {
        return (
              <div>
                <h1 className='mt-8 text-3xl font-bold leading-tight text-gray-800 lg:mb-4 lg:text-4xl'>{val.attributes.title}</h1>
                <p className='text-base font-light text-gray-900 lg:mb-3'>Uploaded by {val.attributes.author} On {val.attributes.date}</p>
                <p className='text-2xl'>{val.attributes.content}</p>
              </div>
        )
      })}
    </div>
  )
}

export async function getStaticProps() {

  const client = new ApolloClient({
    uri: "http://127.0.0.1:1337/graphql",
    cache: new InMemoryCache()
  });

  const { data } = await client.query({
    query: GET_ALL_POSTS
  })

  return {
    props: {
      posts: data.blogPosts.data
    }
  }
}